import { Report } from './types';

const mockA11y = {
  imagesWithAlt: 15,
  imagesWithoutAlt: 3,
  headingOrderIssues: 0,
  ariaLabels: 24,
  missingLangAttr: false,
  contrastIssuesSuspected: false,
};

export const MOCK_REPORT: Report = {
  id: 'demo',
  url: 'https://stripe.com',
  domain: 'stripe.com',
  createdAt: new Date().toISOString(),
  expiresAt: null,
  favicon: 'https://stripe.com/favicon.ico',
  pageTitle: 'Stripe | Financial Infrastructure for the Internet',
  aiEnabled: true,
  scores: {
    messaging: 88,
    seo: 79,
    cro: 82,
    accessibility: 74,
    overall: 81,
  },
  recommendations: [
    { id: 'r1', category: 'SEO', title: 'Add structured data (JSON-LD)', description: 'Structured data helps search engines understand your content and enables rich results. Add Organization, Product, and FAQ schema to improve click-through from search.', impact: 'High', effort: 'Medium', priority: 1 },
    { id: 'r2', category: 'CRO', title: 'Add social proof above the fold', description: 'Customer logos, review counts, or a "trusted by X companies" statement visible without scrolling increases trust and conversion rates significantly.', impact: 'High', effort: 'Low', priority: 2 },
    { id: 'r3', category: 'Accessibility', title: 'Add alt text to 3 images', description: '3 images on the homepage are missing alt text attributes. Alt text is required for screen reader users and also helps SEO image indexing.', impact: 'Medium', effort: 'Low', priority: 3 },
    { id: 'r4', category: 'Performance', title: 'Defer non-critical JavaScript', description: 'Several third-party scripts load synchronously and block page rendering. Moving analytics and chat scripts to defer/async improves perceived load time.', impact: 'Medium', effort: 'Low', priority: 4 },
    { id: 'r5', category: 'Content', title: 'Add a FAQ section to pricing page', description: 'Objection handling through FAQs on the pricing page addresses common buying concerns before they become blockers, reducing sales cycle length.', impact: 'Medium', effort: 'Low', priority: 5 },
    { id: 'r6', category: 'SEO', title: 'Improve meta descriptions on product pages', description: 'Several product pages have missing or auto-generated meta descriptions. Custom descriptions improve click-through rates from search results.', impact: 'Medium', effort: 'Medium', priority: 6 },
    { id: 'r7', category: 'Technical', title: 'Implement canonical tags consistently', description: 'Pages with query parameters lack canonical tags, creating duplicate content issues that dilute SEO authority.', impact: 'High', effort: 'Low', priority: 7 },
    { id: 'r8', category: 'CRO', title: 'Reduce signup form fields', description: 'The signup form collects more info than needed upfront. Progressive profiling typically increases completion rates 10–25%.', impact: 'High', effort: 'Medium', priority: 8 },
    { id: 'r9', category: 'Messaging', title: 'Make pricing page headline benefit-focused', description: 'The pricing page headline leads with features rather than outcomes. Rewriting to focus on what customers gain improves emotional resonance.', impact: 'Medium', effort: 'Low', priority: 9 },
    { id: 'r10', category: 'SEO', title: 'Create topic clusters around core use cases', description: 'Adding pillar pages and supporting content clusters around key topics improves topical authority for competitive terms.', impact: 'High', effort: 'High', priority: 10 },
  ],
  aiInsights: {
    executiveSummary: 'Stripe is a leading financial infrastructure platform targeting developers and businesses building internet-enabled commerce. The site effectively communicates technical sophistication and enterprise trust, with a strong emphasis on developer experience and global payment capabilities.',
    messagingAnalysis: "Stripe's messaging is clear and developer-centric. The primary value proposition — \"Financial infrastructure for the internet\" — is concise and differentiating. The homepage sequences from broad appeal to specific features effectively, but could lead with business outcomes rather than technical capabilities.",
    targetAudience: 'Software developers, CTOs/engineering leads, and business owners at startups through enterprise companies building payment-enabled products. Secondary: CFOs and finance teams evaluating payment infrastructure.',
    topFindings: [
      'Strong technical credibility signaling throughout the site',
      'CTA hierarchy is clear but could be more aggressive above the fold',
      'Excellent use of social proof (brand logos, transaction volumes)',
      'SEO foundation is solid; opportunity for deeper topic coverage',
      '3 images missing alt text attributes affect accessibility score',
    ],
    aiRecommendations: [
      { id: 'ai-1', category: 'CRO', title: 'Add ROI calculator to pricing page', description: 'SaaS buyers respond strongly to calculators that quantify savings. A simple "calculate your fees" tool on the pricing page can increase qualified demo requests by 20–30%.', impact: 'High', effort: 'Medium', priority: 1 },
      { id: 'ai-2', category: 'Messaging', title: 'Segment homepage messaging by company size', description: 'The current homepage speaks broadly to all business sizes. A persona-based navigation (Startup / Scale-up / Enterprise) with tailored value props can significantly reduce bounce rates.', impact: 'High', effort: 'High', priority: 2 },
      { id: 'ai-3', category: 'Content', title: 'Add case study snippets to feature pages', description: 'Feature pages are heavily technical but light on social proof. Adding a mini case study (company + metric) per feature increases conversion of high-intent visitors.', impact: 'Medium', effort: 'Medium', priority: 3 },
    ],
  },
  siteMetrics: {
    pagesCount: 12,
    hasSitemap: true,
    hasRobotsTxt: true,
    robotsAllowed: true,
    hasPricingPage: true,
    hasContactPage: true,
    hasBlogPage: true,
    totalImages: 87,
    totalScripts: 24,
    totalWords: 8430,
    uniqueInternalLinks: 143,
    crawlDurationMs: 8200,
    isJsRendered: false,
    siteType: 'saas',
    performance: {
      source: 'pagespeed',
      performanceScore: 72,
      lcp: 2800,
      fcp: 1200,
      cls: 0.04,
      tti: 4100,
      estimatedScripts: 24,
      estimatedImages: 87,
    },
    techStack: {
      cms: [],
      frameworks: ['React', 'Next.js'],
      trackers: ['Google Analytics', 'Google Tag Manager'],
      cdns: ['Cloudflare'],
      chatWidgets: [],
    },
    securityHeaders: {
      https: true,
      hsts: true,
      csp: true,
      xFrameOptions: 'SAMEORIGIN',
      xContentTypeOptions: true,
      referrerPolicy: 'strict-origin-when-cross-origin',
    },
    brokenLinks: [],
    duplicateTitles: [],
    duplicateMetas: [],
    crawledPages: [
      {
        url: 'https://stripe.com',
        title: 'Stripe | Financial Infrastructure for the Internet',
        metaDescription: 'Stripe powers online and in-person payment processing and financial solutions for businesses of all sizes.',
        canonical: 'https://stripe.com/',
        h1: ['Financial infrastructure for the internet'],
        h2: ['Start today. Launch in weeks', 'Payments for any business', 'Start and scale with ease'],
        h3: ['Accept payments', 'Manage subscriptions', 'Fight fraud'],
        wordCount: 1240,
        internalLinks: [],
        externalLinksCount: 4,
        formsCount: 1,
        inputTypes: ['email'],
        ctaCandidates: ['Start now', 'Contact sales', 'Learn more'],
        scriptSrcs: [],
        imageCount: 18,
        statusCode: 200,
        accessibility: mockA11y,
        hasViewportMeta: true,
        ogTags: {
          title: 'Stripe | Financial Infrastructure for the Internet',
          description: 'Stripe powers online and in-person payment processing and financial solutions for businesses of all sizes.',
          image: 'https://stripe.com/img/v3/home/twitter.png',
          type: 'website',
        },
        twitterCard: 'summary_large_image',
      },
    ],
  },
};
